### ISSUE TITLE
Nonnegative Tucker Decomposition error

### ISSUE THREAD

**Issue by iamjli** [JeanKossaifi/tensorly-notebooks#4]
Hello! I am receiving an error when performing nonnegative Tucker decomposition. Regular Tucker decomposition works fine, and so does PARAFAC and nonnegative PARAFAC.

![image](https://user-images.githubusercontent.com/7219365/38912893-e7c97944-42a5-11e8-9167-4e4e995bde5c.png)

**Comment by JeanKossaifi** [comment]
Hey @iamjli,
This would probably be best posted in the main tensorly repo. The issue comes from the fact that you are only passing one rank (int) instead of a list (one rank for each of the three modes, i.e. the dimension of the core). Also you probably want to assign the result to a core and a list of factors. 

In code:
```python
core, factors = non_negative_tucker(X, ranks=[2, 2, 2])
```

The error should be more informative though and we could use the rank provided for all modes, will change this!
